print('Hello! My name is Guy_bot')
print('I was created in 2021_year')
print('Please, remind me your name')
name = str(input())
print('What a great name you have, ' + name + "!")
print("Let me guess your age")
print("Enter remainders of divining your age by 3, 5 and 7")
a = int(input())
b = int(input())
c = int(input())
age = (a*70+b*21+c*15)%105
print("Your age is " + str(age) + " that's a good time to start programming!")